"""add description and category to products

Revision ID: a931251f397f
Revises: 568870ea86f3
Create Date: 2026-02-05 21:49:26.944518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a931251f397f'
down_revision: Union[str, Sequence[str], None] = '568870ea86f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('orders', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('billing_address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['invoice_number'])
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'description')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'billing_address')
    op.drop_column('orders', 'invoice_number')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'total_amount')
    # ### end Alembic commands ###
